--Total customers by country
SELECT Country,COUNT(Customer_Key) AS Total_customers
FROM gold.Customer_Dim
GROUP BY Country
ORDER BY Total_customers DESC

--Total customers by Gender
SELECT Gender,COUNT(Customer_Key) AS Total_customers
FROM gold.Customer_Dim
GROUP BY Gender
ORDER BY Total_customers DESC

--Total Products per category
SELECT Category,COUNT(Product_Key) AS Total_Products
FROM gold.Product_Dim
GROUP BY Category
ORDER BY Total_Products DESC


--Average Cost per category
SELECT Category,AVG(Cost) AS Average_Cost
FROM gold.Product_Dim
GROUP BY Category
ORDER BY Average_Cost DESC

--Total Revenue for each category
SELECT Category,Sum(Sales_Amount) AS Total_revenue
FROM gold.Fact_Sales f Left JOIN
gold.Product_Dim p ON f.Product_Key=p.Product_Key
GROUP BY Category
ORDER BY Total_revenue DESC

--Total Revenue generated by each category
SELECT c.Customer_Key,c.First_Name,c.Last_Name,Sum(Sales_Amount) AS Total_revenue
FROM  gold.Fact_Sales f Left JOIN
gold.Customer_Dim c ON c.Customer_Key=f.Customer_Key
GROUP BY c.Customer_Key,c.First_Name,c.Last_Name
ORDER BY Total_revenue DESC


--Distribution of sold items acrss countries
SELECT c.Country,SUM(Quantity) AS Total_Quantity
FROM gold.Fact_Sales f LEFT JOIN
gold.Customer_Dim c 
ON c.Customer_Key=f.Customer_Key
GROUP BY c.Country
ORDER BY Total_Quantity DESC